---
- name: Start collectd
  service:
    name: collectd
    state: started
    enabled: true

- name: Stop collectd
  service:
    name: collectd
    state: stopped
    enabled: true

- name: Restart collectd
  service:
    name: collectd
    state: restarted
    enabled: true
